using System.Collections.Generic;

namespace ead_frontend.Models
{
    public class Catalog
    {
        public List<string[]> Locations { get; set; }

        public Catalog()
        {
            Locations = new List<string[]>
            {
                new string[2] {"AVAIL_SOON", "Item being cataloged"},
                new string[2] {"BINDERY", "Item at the bindery"},
                new string[2] {"CATALOGING", "Item being cataloged"},
                new string[2] {"CHECKEDOUT", "Item has been checked out"},
                new string[2] {"DAMAGED", "Item is damaged"},
                new string[2] {"DAMAGED629", "Damaged 6/29/2014"},
                new string[2] {"DISCARD", "Withdrawn from the collection"},
                new string[2] {"HAV", "Ask for item at Laupus Circulation Desk"},
                new string[2] {"HAVMOD", "Ask for item at Laupus Circulation Desk"},
                new string[2] {"HCHSRD", "Center for Health Services Research & Development"},
                new string[2] {"HCJOUR", "Current Journals"},
                new string[2] {"HEQUIP", "Ask for item at Laupus Service Desk"},
                new string[2] {"HFICHE", "Microfiche"},
                new string[2] {"HHDISPLAY", "History Display Case"},
                new string[2] {"HHOLDS", "Item is on hold"},
                new string[2] {"HHUC", "Ask for item at Laupus Service Desk"},
                new string[2] {"HJFILM", "Microfilm"},
                new string[2] {"HJOUR", "Journals - Stacks"},
                new string[2] {"HLAB", "Computer Lab"},
                new string[2] {"HMHAD", "Laupus monthly health awareness display"},
                new string[2] {"HMISSING", "Missing - search in progress"},
                new string[2] {"HNCAI", "North Carolina Agromedicine Institute"},
                new string[2] {"HNEWBOOKS", "New Book Shelf"},
                new string[2] {"HOLDS", "Item is on hold"},
                new string[2] {"HREF", "Reference - Does not circulate"},
                new string[2] {"HRV", "Laupus Reserve"},
                new string[2] {"HRVEQUIP", "Processing for next borrower"},
                new string[2] {"HSLBK", "Books - Stacks"},
                new string[2] {"HSLBKO", "Oversize Books - Stacks"},
                new string[2] {"HSLBKPR", "Popular Reading Collection"},
                new string[2] {"HSLELEC", "Electronic Resources"},
                new string[2] {"HSLHCR", "History Collection Book Repair"},
                new string[2] {"HSLHICF", "History Collection - Flat Oversize - Does not circulate"},
                new string[2] {"HSLHICO", "History Collection - Oversize - Does not circulate"},
                new string[2] {"HSLHIND", "History Collection Indexes - Does not circulate"},
                new string[2] {"HSLHIRO", "History Reading Room - Oversize - Does not circulate"},
                new string[2] {"HSLHIRR", "History Reading Room - Does not circulate"},
                new string[2] {"HSLHISJ", "History Journals - Does not circulate"},
                new string[2] {"HSLHISM", "History Collection Manuscripts - Does not circulate"},
                new string[2] {"HSLHISR", "History Collection Reference - Does not circulate"},
                new string[2] {"HSLHIST", "History Collection Books - Does not circulate"},
                new string[2] {"HSLHMUSA", "Country Doctor Museum Archives Collection - Does not circulate"},
                new string[2] {"HSLHMUS", "Country Doctor Museum - Does not circulate"},
                new string[2] {"ILL", "Item is on loan to another library"},
                new string[2] {"INPROCESS", "Item being cataloged"},
                new string[2] {"INSHIPPING", "Item being shipped to destination"},
                new string[2] {"INTRANSIT", "Item being transferred between libraries"},
                new string[2] {"JASKTRC", "Ask at TRC Desk"},
                new string[2] {"JBND", "Bindery"},
                new string[2] {"JCAT", "Cataloging"},
                new string[2] {"JCDV", "Collection Development"},
                new string[2] {"JCP", "Current Periodicals"},
                new string[2] {"JCPS", "Compact Journals - Ask at Circulation Desk"},
                new string[2] {"JCPSBPP", "Compact British Parliament Papers"},
                new string[2] {"JCPSO", "Compact Stacks Oversize - Ask at Circulation Desk"},
                new string[2] {"JCPSR", "Compact Reference - Basement"},
                new string[2] {"JCPS2", "Compact Stacks - Ask at Circulation Desk"},
                new string[2] {"JCUAS", "TRC Mixed Media"},
                new string[2] {"JCUB", "TRC Big Books"},
                new string[2] {"JCUBIO", "TRC Biographies"},
                new string[2] {"JCUEASY", "TRC Easy Picture Books"},
                new string[2] {"JCUFIC", "TRC Fiction"},
                new string[2] {"JCUGR", "TRC Guided Reading"},
                new string[2] {"JCUNONFIC", "TRC Nonfiction"},
                new string[2] {"JCUP", "TRC Professional"},
                new string[2] {"JCUR", "TRC Reference"},
                new string[2] {"JCURA", "TRC Reserve Rare"},
                new string[2] {"JCURV", "TRC Curriculum Review"},
                new string[2] {"JCUSP", "TRC Special Books"},
                new string[2] {"JCUT", "TRC NC Supplemental Textbooks"},
                new string[2] {"JCUTA", "TRC Curriculum Teaching Aids"},
                new string[2] {"JCUTR", "TRC NC Adopted Textbooks"},
                new string[2] {"JDISPCIRC", "Display - Ask at Circulation Desk"},
                new string[2] {"JDISPLEAD", "Leadership Display - First Floor Reading Lounge"},
                new string[2] {"JDISPMUSIC", "Music Display - First Floor Reading Lounge"},
                new string[2] {"JDISPSC", "Display - Ask at Joyner Special Collections Reference Desk"},
                new string[2] {"JDISPTHEME", "Themed Display - First Floor Reading Lounge"},
                new string[2] {"JDISPTRC", "Display - Ask at TRC Desk"},
                new string[2] {"JDOCMI", "Microforms B300"},
                new string[2] {"JDOCOE", "Fed Docs CWIS"},
                new string[2] {"JDOMA", "Fed Docs Maps"},
                new string[2] {"JDOMAI", "Fed Docs Map Indexes"},
                new string[2] {"JDOMI", "Microforms B300"},
                new string[2] {"JDOO", "Fed Docs Office"},
                new string[2] {"JDOOCD", "Fed Docs CD-ROMs"},
                new string[2] {"JDOR", "Fed Docs Reference"},
                new string[2] {"JDOS", "Fed Docs Stacks"},
                new string[2] {"JDOSFO", "Fed Docs General Stacks - Flat Oversize"},
                new string[2] {"JDOSO", "Fed Docs General Stacks - Oversize"},
                new string[2] {"JETCROOM", "TRC ETC Room"},
                new string[2] {"JGES", "General Stacks"},
                new string[2] {"JGESFO", "General Stacks - Flat Oversize"},
                new string[2] {"JGESO", "General Stacks - Oversize"},
                new string[2] {"JHOLDS", "Item is on hold"},
                new string[2] {"JINC", "Ask at Circulation Desk"},
                new string[2] {"JINCIS", "Circulation Inventory Shelf"},
                new string[2] {"JMESD", "Compact DVDs"},
                new string[2] {"JMESV", "Compact VHS"},
                new string[2] {"JMEV", "TRC Reserve Miscellaneous"},
                new string[2] {"JMF", "Microforms B300"},
                new string[2] {"JMFNP", "Microforms - Newspaper Collection"},
                new string[2] {"JMFG", "Microform Collection Guides (B300)"},
                new string[2] {"JMFOT", "Microforms"},
                new string[2] {"JMMF", "Microforms - Music Collection"},
                new string[2] {"JMISSING", "Missing - search in progress"},
                new string[2] {"JNCB", "NC Broadsides"},
                new string[2] {"JNCCP", "NC Current Periodicals"},
                new string[2] {"JNCD", "NC Documents"},
                new string[2] {"JNCM", "NC Maps"},
                new string[2] {"JNCMF", "NC Microforms"},
                new string[2] {"JNCMFICHE", "NC Microfiche"},
                new string[2] {"JNCMO", "NC Maps - Oversize"},
                new string[2] {"JNCMU", "NC Multimedia Stacks"},
                new string[2] {"JNCP", "NC Prints"},
                new string[2] {"JNCRA", "NC Rare"},
                new string[2] {"JNCRAO", "NC Rare - Oversize"},
                new string[2] {"JNCRE", "NC Reference"},
                new string[2] {"JNCREO", "NC Reference - Oversize"},
                new string[2] {"JNCRO", "NC Roberts"},
                new string[2] {"JNCS", "NC Stacks"},
                new string[2] {"JNCSO", "NC Stacks - Oversize"},
                new string[2] {"JNET", "Electronic Resources"},
                new string[2] {"JNEWBOOKS", "New Books"},
                new string[2] {"JPARK", "Joyner \"Parking Lot\" for Possible Title Replacement"},
                new string[2] {"JPR", "Popular Reading Collection"},
                new string[2] {"JPULL", "Item pulled for review"},
                new string[2] {"JRB", "TRC Ronnie Barnes Collection"},
                new string[2] {"JRBLC", "TRC Ronnie Barnes Collection"},
                new string[2] {"JREA", "Reference Oversize"},
                new string[2] {"JREB", "Reference Business"},
                new string[2] {"JRED", "Reference Desk"},
                new string[2] {"JREL", "Reference Wall"},
                new string[2] {"JRES", "Reference Stacks"},
                new string[2] {"JRV", "Joyner Reserve"},
                new string[2] {"JRVEQUIP", "Processing for next borrower"},
                new string[2] {"JRVHOLD", "Joyner Reserve"},
                new string[2] {"JRVP", "Item awaiting reserve processing"},
                new string[2] {"JSCA", "Special Collections Authors"},
                new string[2] {"JSCDR", "Special Collections Drawings"},
                new string[2] {"JSCH", "Hoover Collection"},
                new string[2] {"JSCHA", "Havelock Collection"},
                new string[2] {"JSCHFO", "Hoover Collection - Flat Oversize"},
                new string[2] {"JSCHO", "Hoover Collection - Oversize"},
                new string[2] {"JSCJ", "University Archives"},
                new string[2] {"JSCMA", "Special Collections Map Cases"},
                new string[2] {"JSCQ", "Manuscript Collection"},
                new string[2] {"JSCR", "Rare Collection"},
                new string[2] {"JSCRAB", "Rare Artist's Book Collection"},
                new string[2] {"JSCRE", "Special Collections Reference"},
                new string[2] {"JSCREALIA", "Special Collections Realia"},
                new string[2] {"JSCREO", "Special Collections Reference - Oversize"},
                new string[2] {"JSCRO", "Rare Collection - Oversize"},
                new string[2] {"JSCRV", "Rare Vault"},
                new string[2] {"JSCRVLC", "Rare Vault"},
                new string[2] {"JSCS", "Schlobin Fantasy Collection"},
                new string[2] {"JSCSO", "Schlobin Fantasy Collection - Oversize"},
                new string[2] {"JSCW", "Stuart Wright Collection"},
                new string[2] {"JVBP", "Veterans Book Project"},
                new string[2] {"JWEED", "Collection Development ? item considered for removal"},
                new string[2] {"JWP", "Wachovia Partnership East"},
                new string[2] {"JYBPDDAP", "Order on Demand Title"},
                new string[2] {"LONGOVRDUE", "Item long overdue"},
                new string[2] {"LOST", "Item is lost"},
                new string[2] {"LOST-ASSUM", "Item is assumed lost"},
                new string[2] {"LOST-CLAIM", "Item is claimed to be lost"},
                new string[2] {"LOST-PAID", "Lost and paid for"},
                new string[2] {"MAV", "Audiovisual Equipment"},
                new string[2] {"MCM", "Choral Music Collection"},
                new string[2] {"MCP", "Current Periodicals - Technology Lab"},
                new string[2] {"MCS", "Closed Stacks - Ask at Circulation Desk"},
                new string[2] {"MDE", "Ask at Circulation Desk"},
                new string[2] {"MDIGITIZE", "Temporarily Unavailable"},
                new string[2] {"MDISPLAY", "Display - Ask at Music Circulation Desk"},
                new string[2] {"MHOLDS", "Item is on hold"},
                new string[2] {"MISSING", "Missing - search in progress"},
                new string[2] {"MME", "Music Media - Ask at Circulation Desk"},
                new string[2] {"MMF", "Remote Storage - Ask at Circulation Desk"},
                new string[2] {"MMISSING", "Missing - search in progress"},
                new string[2] {"MMS", "Miniature Scores"},
                new string[2] {"MNET", "Electronic Resource"},
                new string[2] {"MOV", "Oversize - Ask at Circulation Desk"},
                new string[2] {"MRE", "Reference"},
                new string[2] {"MREM", "Remote Storage - Ask at Circulation Desk"},
                new string[2] {"MREMLC", "Remote Storage- Ask at Circulation Desk"},
                new string[2] {"MRV", "Music Reserve"},
                new string[2] {"MRVHOLD", "Music Equipment - Ask at Circulation Desk"},
                new string[2] {"MRVM", "Music Reserve"},
                new string[2] {"MRVP", "Item awaiting reserve processing"},
                new string[2] {"MSC", "Special Collections - Ask at Circulation Desk"},
                new string[2] {"MSCLC", "Special Collections - Ask at Circulation Desk"},
                new string[2] {"MSM", "Sheet Music Collection"},
                new string[2] {"MST", "Music Stacks"},
                new string[2] {"MTEMPOUT", "Temporarily Unavailable"},
                new string[2] {"NEWBOOKS", "New Books"},
                new string[2] {"ON-ORDER", "Item is on order"},
                new string[2] {"REFERENCE", "Reference Material"},
                new string[2] {"REPAIR", "Item is being repaired"},
                new string[2] {"RESERVES", "Item is on reserve"},
                new string[2] {"RESHELVING", "Item is being re-shelved"},
                new string[2] {"STACKS", "Standard shelving location"}

            };
        }
    }
}